enableGlobalCache: true

nodeLinker: pnp

packageExtensions:
  "@miniflare/r2@*":
    dependencies:
      "@miniflare/core": ^2.12.1

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-4.0.0-rc.42.cjs
